services:
  django:
    stdin_open: true
    tty: true
    build:
      context: ../../
      dockerfile: docker/dev/django.Dockerfile
    env_file:
      - ../../env/dev/.env
    image: django-project-dev:latest
    container_name: django-project-dev
    volumes:
      - ../../app:/app
    ports:
      - "8000:8000"
