# Generated by Django 5.2.2 on 2025-07-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(default='default', help_text="Template name without extension, e.g. 'about' or 'contact'", max_length=16, verbose_name='Template'),
        ),
    ]
